### PR TITLE
Use proper allowedAction term.

### LINKED ISSUE #4: Delegate is using `allowedActions` rather than `allowedAction`.
The `delegate` method on ZcapClient appears to be using an incorrect term when constructing and signing the zcap. 
https://github.com/digitalbazaar/ezcap/blob/d26656660d903d1409b4851dccb647264a6c49f1/lib/ZcapClient.js#L135-L137
This throws an error when the zcap is signed by jsonld signatures.

https://github.com/w3c-ccg/security-vocab/blob/e2302802b5cce3d853e3e909e2d5cc0f1b46e62f/contexts/security-v2.jsonld#L28

### PR DESCRIPTION
**Pull request by tolson4**
fixes #4 

Note that the unit tests in this PR are failing because the branch of `did-method-key` used in testing no longer exists. It looks like @mattcollier has fixed the unit tests in #3 so they were not addressed as part of this PR.

### CODE REVIEW

File: lib/ZcapClient.js [hunk 1]
```diff
@@ -132,8 +132,8 @@ export class ZcapClient {
       };
     }
 
-    if(allowedActions.length > 0) {
-      delegatedCapability.allowedActions = allowedActions;
+    if(allowedAction.length > 0) {
+      delegatedCapability.allowedAction = allowedAction;
```
Comment (dlongley) [inline lib/ZcapClient.js:136]: Actually, I recommend we only change this one line. The data model uses `allowedAction` as that is idiomatic there, but using plural form in the API is also idiomatic. So I suggest this PR just adjust the one line here to use singular on `delegatedCapability`, leaving the docs and API the same.

**Review by dlongley — CHANGES_REQUESTED** [review]

**Review by dlongley — APPROVED** [review]
Thanks!

**Review by dmitrizagidulin — APPROVED** [review]
:+1:
